#!/bin/bash
## Upgrade inventory variables to the latest version of ypid-ansible-inventory
## The script is idempotent.

git ls-files -z "$(git rev-parse --show-toplevel)" | xargs --null -I '{}' find '{}' -type f -print0 \
 | xargs --null sed --in-place --regexp-extended '
     s/inventory__apt_default_mirrors/ansible_facts__apt__default_mirrors/g;
   '
