---
# vim: foldmarker=[[[,]]]:foldmethod=marker

# Common adjustments for using DebOps to manage workstations.

# Don’t setup a realm for the host, it probably won’t need it.
# It can still take part in the internal CA.
pki_default_realms: []
pki_scheduler: False

# Systems might have public IP addresses (v6) but that does not mean that you
# want to run ACME on them.
pki_acme: False

# We will probably not need DH params at all.
# If needed, the custom DH params generated on the Ansible controller will
# still be available.
dhparam__generate_cron: False
dhparam__generate_init: False
dhparam__deploy_state: 'absent'

# No need to run a fully featured NTP daemon on each workstation.
# Just sync the time once when a interface comes up.
ntp__daemon: 'ntpdate'

# Always get the latest and gradest provided by a distribution release.
unattended_upgrades__release: True

# Silently ignore unreachable APT proxies.
apt_proxy__temporally_avoid_unreachable: True

# In case the workstation happens to be in `debops_service_ifupdown`:
# Do not configure network using ifupdown. This should be manage by the end
# user using network-manager.
ifupdown__ethernet_interfaces: {}
ifupdown__default_interfaces: {}

# Get the latest and greatest application versions but keep the base system on
# rock solid Debian stable :)
packages__apt_preferences__backports_state: 'present'

# Even faster boot time.
grub__timeout_hardware: 1

# Reset hidepid from 2 (DebOps default) to 0 (Linux and Debian default) for
# Polkit to work.
# Ref: https://github.com/debops/debops/pull/2509
proc_hidepid__level: '0'

# TODO list:
#
# * https://freedesktop.org/wiki/Software/systemd/Optimizations/
#   * Testing: Remove rsyslog
#   * Testing: Remove exim4
